config/routes.rb
NexusTest::Application.routes.draw do
  resources :courses

  get "course_search/search"

	root to: 'xcri_cap_lookup#index'

end

app/models/course.rb
class Course < ActiveRecord::Base



end

app/models/xcri_cap.rb
require 'nokogiri'
class XcriCap
	attr_reader :message, :contributor, :description, :provider_description, :provider_url, :provider_identifier, :provider_title, :course_title, :course_desc, :course_subject, :course_identifier, :course_type, :course_url, :course_abstract, :course_application_procedure
	def initialize(id)

		client = Savon::Client.new(wsdl: "http://www.hefty.ws/services/GetCourses?wsdl")
		response = client.call(:get_course_by_id, message: { "courseid" => id })
		#client = Savon::Client.new(wsdl: "http://www.webservicex.net/uszip.asmx?WSDL")
    #response = client.request :web, :get_info_by_zip, body: { "USZip" => id }
    #response = client.call(:get_info_by_zip, message: { "USZip" => id })
		if response.success?
    	#data = response.to_array(:get_info_by_zip_response, :get_info_by_zip_result, :new_data_set, :table).first
			data = response.to_hash[:catalog]#[:get_info_by_zip_result][:new_data_set][:table]	    
			#provider = response.to_hash[:catalog][:provider]
			courses = response.to_array(:catalog, :provider, :course)
			#doc = response.doc
			if data
				@contributor = data[:contributor]
				@description = data[:description]
				@provider_description = data[:provider][:description]
				@provider_url = data[:provider][:url]
				@provider_identifier = data[:provider][:identifier]
				@provider_title = data[:provider][:title]

				#courses.each do |r|
					if courses.empty?
						@message = "No results returned."	
					else
						if courses.count > 1
							@message = "First of " + courses.count.to_s + " results."
							@course_title = courses[0].to_hash[:title]
							@course_type = courses[0].to_hash[:type]
              @course_identifier = courses[0].to_hash[:identifier]
              @course_subject = courses[0].to_hash[:subject]
              @course_desc = courses[0].to_hash[:description]
              @course_url = courses[0].to_hash[:url]
              @course_abstract = courses[0].to_hash[:abstract]
              @course_application_procedure = courses[0].to_hash[:applicationProcedure]
						else
							@message = "1 result."
							@course_title = data[:provider][:course][:title]
							@course_type = data[:provider][:course][:type]
							@course_identifier = data[:provider][:course][:identifier]
							@course_subject = data[:provider][:course][:subject]
							@course_desc = data[:provider][:course][:description]
							@course_url = data[:provider][:course][:url]
							@course_abstract = data[:provider][:course][:abstract]
							@course_application_procedure = data[:provider][:course][:applicationProcedure]
						end
					end
			end
#		else
#			@message = "No results returned"
		end
					#doc.css('course').first do |co|
					#	@coursedesc = co.to_hash[:description]
					#end
#			end
#	    end
#    end

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/course_search_controller.rb
class CourseSearchController < ApplicationController
  def search
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :ok }
    end
  end
end

app/controllers/xcri_cap_lookup_controller.rb
class XcriCapLookupController < ApplicationController
	  def index
			    @xcri_cap = XcriCap.new(params[:xcri_cap]) if params[:xcri_cap].present?
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_search_helper.rb
module CourseSearchHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/course_search/search.html.erb
<h1>Course Search</h1>
<p> search form goes here </p>

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_area :summary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Summary</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @courses.each do |course| %>
  <tr>
    <td><%= course.id %></td>
    <td><%= course.name %></td>
    <td><%= course.summary %></td>
    <td><%= link_to 'Show', course %></td>
    <td><%= link_to 'Edit', edit_course_path(course) %></td>
    <td><%= link_to 'Destroy', course, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @course.id %>
</p>

<p>
  <b>Name:</b>
  <%= @course.name %>
</p>

<p>
  <b>Summary:</b>
  <%= @course.summary %>
</p>


<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NexusTest</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div id="container">
		    <% flash.each do |name, msg| %>
					      <%= content_tag :div, msg, :id => "flash_#{name}" %>
		    <% end %>
		    <%= yield %>
  </div>

</body>
</html>

app/views/xcri_cap_lookup/index.html.erb
<h1>Xcri Cap: Course Id Lookup</h1>
<%= form_tag root_url, method: :get do %>
	<p>
	  <%= text_field_tag :xcri_cap, params[:xcri_cap] %>
	  <%= submit_tag "Lookup", name: nil %>
	</p>
<% end %>

<% if @xcri_cap %>
	 <%= @xcri_cap.message %>
	<dl id ="xcri_cap_info">
		<h2>Catalog</h2>
		<dt>Contributor:</dt>
		<dd><%= @xcri_cap.contributor %></dd>
		<dt>Description:</dt>
		<dd><%= @xcri_cap.description %></dd>

		<h2>Provider</h2>
		<dt>Title:</dt>
		<dd><%= @xcri_cap.provider_title %></dd>
		<dt>Description:</dt>
		<dd><%= @xcri_cap.provider_description %></dd>
		<dt>Url:</dt>
    <dd><%= @xcri_cap.provider_url %></dd>
		<dt>Identifier:</dt>
    <dd><%= @xcri_cap.provider_identifier %></dd>

		<h2>Course</h2>
		<dt>Title:</dt>
		<dd><%= @xcri_cap.course_title %></dd>
		<dt>Description:</dt>
		<dd><%= @xcri_cap.course_desc %></dd>
		<dt>Subject:</dt>
		<dd><%= @xcri_cap.course_subject %></dd>
		<dt>Identifier:</dt>
		<dd><%= @xcri_cap.course_identifier %></dd>
		<dt>URL:</dt>
		<dd><%= @xcri_cap.course_url %></dd>
	</dl>
<% end %>